spring:
  application:
    name: payment-api
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db:changelog-master:xml
  main:
    allow-bean-definition-overriding: true

#PCI-PAL
pci-pal:
  account.id:
    cmc: ${PCI_PAL_ACCOUNT_ID_CMC:cmc}
    probate: ${PCI_PAL_ACCOUNT_ID_PROBATE:probate}
  account.id.divorce: ${PCI_PAL_ACCOUNT_ID_DIVORCE:divorce}
  api:
    url: ${PCI_PAL_API_URL:https://pci-pal.url.com}
    key: ${PCI_PAL_API_KEY:pci-pal-api-key}
  callback-url: ${PCI_PAL_CALLBACK_URL:pci-pal-callback-url}
paybubble.home.url: ${PAYBUBBLE_HOME_URL:https://test.url.com}

# Liberata
liberata:
  api.account.url: ${LIBERATA_API_ACCOUNT_URL:https://bpacustomerportal.liberata.com/pba/public/api/v2/account}
  oauth2:
    client:
      id: ${LIBERATA_OAUTH2_CLIENT_ID:id}
      secret: ${LIBERATA_OAUTH2_CLIENT_SECRET:secret}
    username: ${LIBERATA_OAUTH2_USERNAME:username}
    password: ${LIBERATA_OAUTH2_PASSWORD:password}
    base.url: ${LIBERATA_OAUTH2_BASE_URL:https://bpacustomerportal.liberata.com/pba/public/api/v2}
    authorize.url: ${LIBERATA_OAUTH2_AUTHORIZE_URL:https://bpacustomerportal.liberata.com/pba/public/oauth/authorize}
    token.url: ${LIBERATA_OAUTH2_TOKEN_URL:https://bpacustomerportal.liberata.com/pba/public/oauth/token}

gov:
  pay:
    auth.key:
      cmc: ${GOV_PAY_AUTH_KEY_CMC:#{cmc_key}}
      probate_frontend: ${GOV_PAY_AUTH_KEY_PROBATE_FRONTEND:#{probate_key}}
      divorce_frontend: ${GOV_PAY_AUTH_KEY_DIVORCE_FRONTEND:#{divorce_key}}
    url: ${GOV_PAY_URL:#{https://publicapi.payments.service.gov.uk/v1/payments}}
    operational_services: ${GOV_PAY_OPERATIONAL_SERVICES:#{ccd_gw,api_gw}}

# S2S trusted services
trusted.s2s.service.names: cmc,probate_frontend,divorce_frontend,ccd_gw,bar_api,api_gw,finrem_payment_service,ccpay_bubble,jui_webapp

auth:
  idam.client.baseUrl: ${AUTH_IDAM_CLIENT_BASEURL:#{http://dummy.dummy.net}}
  provider.service.client.baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:#{http://dummy.dummy.net}}

card:
  payments:
    report:
      startDate: ${CARD_PAYMENTS_REPORT_START_DATE:#{null}}
      endDate: ${CARD_PAYMENTS_REPORT_END_DATE:#{null}}

management:
  endpoints:
    web:
      base-path: /
      exposure.include: health,info
  endpoint:
    health.show-details: always
  health:
    mail.enabled: false

feature:
  payments:
    search: true
    service.callback: true
  credit.account:
    payment.liberata.check: true
  check:
    liberata.account.for.all.services: false
  duplicate.payment.check: true

duplicate.payment.check.interval.in.minutes:  2

azure:
  application-insights.instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}
  servicebus:
    connection-string: ${ASB_CONNECTION_STRING}
    topic-name: serviceCallbackTopic
    subscription-name: defaultServiceCallbackSubscription
    allow-telemetry: false

# Disable Circuit Breaker (Hystrix)
#spring.cloud.circuit.breaker.enabled: false
#hystrix.command.default.circuitBreaker.enabled: false
