description: Helm chart for the HMCTS payment api
name: payment-api
home: https://github.com/hmcts/ccpay-payment-app
version: 0.0.2
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
