java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"

    SPRING_LIQUIBASE_ENABLED: true
    SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/hmcts
    OIDC_CLIENT_SECRET: NVYEC2X7XFSRENTU
    OIDC_S2S_SECRET: G5XTFNBUW4P6ZP4F
    LAUNCH_DARKLY_USER_NAME_PREFIX: aat

    SPRING_PROFILES_ACTIVE: "liberataMock,callbackMock,ccdMock"
    CALLBACK_PAYMENTS_CUTOFF_TIME_IN_MINUTES: 0

    #Below key required for preview pipeline
    GOV_PAY_AUTH_KEY_CMC: 8ln764q6jrbgqvvvv40uggsea3h1p602v79gdrt7ni66mrmpk416ulohvd
    LAUNCH_DARKLY_SDK_KEY: sdk-06456c8b-312c-475c-b154-ca585f5ca063
    ASB_CONNECTION_STRING: Endpoint=sb://sb-62023c0e-2b32-43c5-b641-e483366f3a27.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=qTu7tq9aDOI47OMlwrP6lpM6FKNlpUrxc860efI3Q6w=
    ASB_TOPIC_NAME: servicecallbacktopic
    ASB_SUBSCRIPTION_NAME: 704b8c02-7252-4559-b2bd-8bc7a8417865
  postgresql:
    enabled: true
